@{
    RootModule        = "PSCoder.psm1"
    ModuleVersion     = "1.0.0"
    GUID              = "7f3e9a2b-4c8d-4e1f-b6a5-9d2c8f1e3a7b"
    Author            = "PSCoder Team"
    Description       = "AI Assistant for PowerShell using OpenRouter API"
    PowerShellVersion = "5.1"
    FunctionsToExport = @(
        "Start-PSCoder"
        "Get-PSCoderConfig"
        "Set-PSCoderConfig"
        "Get-OpenRouterApiKey"
        "Get-GroqApiKey"
        "Get-ModelsList"
        "Invoke-OpenRouterChat"
        "Invoke-GroqChat"
        "Get-GroqModelsList"
        "Invoke-WebSearch"
        "Invoke-WebFetch"
        "Invoke-OcrImage"
        "Initialize-OcrEngine"
        "Invoke-AutoHeal"
        "Add-Learning"
        "Get-Learnings"
        "Find-Solution"
        "Invoke-PSCoderTool"
        "Get-ToolSchemas"
        "Get-ToolNameList"
        "Get-PSCoderMemory"
        "Show-PSCoderMemory"
        "Set-PSCoderMemory"
        "Add-PSCoderMemoryNote"
        "Get-PSCoderSystemPrompt"
        "Invoke-SlashCommand"
        "Show-Help"
        "Get-PSCoderSessionsDir"
        "Save-PSCoderSession"
        "Show-SessionHistory"
        "Load-PSCoderSession"
        "Write-PSCoderBanner"
        "Write-PSCoderPrompt"
        "Write-AssistantMessage"
        "Write-ToolCall"
        "Write-ToolResult"
        "Write-ErrorPS"
        "Write-InfoPS"
        "Write-HeaderPS"
        "Write-WarningPS"
        "Confirm-Action"
        "Get-Cache"
        "Set-Cache"
        "Write-PSCoderLog"
        "Set-PSCoderLogLevel"
        "Clear-PSCoderLog"
        "Get-PSCoderLog"
        "Invoke-AutoCompact"
        "Initialize-Hooks"
        "Invoke-PreToolUseHook"
        "Invoke-PostToolUseHook"
        "Invoke-StopHook"
        "Get-HookLog"
        "Clear-HookLog"
        "Build-GitContext"
        "Build-ProjectMdContext"
        "Build-FullContext"
        "Clear-ContextCache"
        "Set-PermissionMode"
        "Get-PermissionStatus"
        "Add-SessionAllow"
        "Add-SessionDeny"
        "Add-PersistentAllow"
        "Add-PersistentDeny"
        "Remove-PersistentRule"
        "Initialize-Permissions"
        "Initialize-PSCoderConfig"
        "Convert-PSObjectToHashtable"
        "Test-ToolNeedsApproval"
        "Set-ToolAlwaysApproved"
        "Invoke-CreatePlan"
        "Invoke-VerifyStep"
        "Invoke-VerifyTask"
        "Invoke-PlanSummary"
        "Initialize-ReasoningEngine"
        "Initialize-MemoryDecision"
        "Invoke-MemoryDecision"
        "Get-EstimatedCost"
        "Initialize-SkillManager"
        "Get-SkillList"
        "Get-SkillContent"
        "Initialize-InterruptHandler"
        "Test-Interrupt"
        "Clear-Interrupt"
        "Invoke-InterruptCleanup"
        "Invoke-AddPlanStep"
        "Test-PSCoderConfig"
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}
